const mongoose = require("mongoose");
const timestamps = require("mongoose-timestamp");
const objectId = mongoose.Types.ObjectId;
const payRollManualEntry = new mongoose.Schema({
  company_name: { type: String },
  unit_name: { type: String },
  date: { type: String },
  ecode: { type: String },
  ename: { type: String },
  etype: { type: String },
  eac: { type: String },
  ebankname: { type: String },
  eifsc: { type: String },
  designation: { type: String },
  present: { type: String },
  dutyoff: { type: String },
  add_duties: { type: String },
  payment_type: { type: String },
  paymode: { type: String },
  total_duties: { type: String },
  basic: { type: String },
  da: { type: String },
  hra: { type: String },
  trv_ex: { type: String },
  others: { type: String },
  medical: { type: String },
  others1: { type: String },
  others2: { type: String },
  others3: { type: String },
  others4: { type: String },
  waesi: { type: String },
  ewdays: { type: String },
  ewamount: { type: String },
  gross: { type: String },
  advance: { type: String },
  loan: { type: String },
  uniform: { type: String },
  mess: { type: String },
  rent: { type: String },
  atm: { type: String },
  phone: { type: String },
  pf: { type: String },
  esi: { type: String },
  pr_tax: { type: String },
  staff_wellfare: { type: String },
  total_dec: { type: String },
  net_pay: { type: String },
  add_amount: { type: String },
  advance_id: { type: String },
  loan_id: { type: String },
  uniform_id: { type: String },
  mess_id: { type: String },
  rent_id: { type: String },
  atmcard_id: { type: String },
  others_id: { type: String },
  phone_id: { type: String },
});
payRollManualEntry.plugin(timestamps);
mongoose.model("payroll_manual_entry", payRollManualEntry);
module.exports = mongoose.model("payroll_manual_entry");
